INSERT INTO rental_user VALUES(1, 'tom', '000-0000', 'example1@example.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rental_user VALUES(2, 'jerry', '000-0001', 'example2example.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO book VALUES(1, N'ハリーポッター', N'ローリング', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO book VALUES(2, N'キングダム', N'hoge', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);