spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=sampleDb
    username: sa
    password: Password123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: -1
  h2:
    console:
      enabled: true
