spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: none
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: -1
  h2:
    console:
      enabled: true
  jackson:
    time-zone: Asia/Tokyo #リクエストボディ変換には効くがクエリパラメータ変換には効かない