INSERT INTO rental_user VALUES(1, 'tom', '000-0000', 'example1@gmail.com', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO rental_user VALUES(2, 'jerry', '000-0001', 'example2@gmail.com', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO book VALUES(1, 'hoge1', 'author1', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO book VALUES(2, 'hoge2', 'author2', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO book VALUES(3, 'hoge3', 'author3', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO book VALUES(4, 'hoge4', 'author4', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO book VALUES(5, 'hoge5', 'author5', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

--INSERT INTO rental VALUES(1, 1, 1, DATEADD('DAY', 1, CURRENT_DATE), 0, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
--INSERT INTO rental VALUES(2, 2, 1, DATEADD('DAY', 1, CURRENT_DATE), 0, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
--INSERT INTO rental VALUES(3, 3, 1, DATEADD('DAY', 1, CURRENT_DATE), 0, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
--INSERT INTO rental VALUES(4, 4, 2, DATEADD('DAY', 1, CURRENT_DATE), 0, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
--INSERT INTO rental VALUES(5, 5, 2, DATEADD('DAY', 1, CURRENT_DATE), 0, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

